
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 2
    labels:
      - "type:maintenance"
      - "dependencies"
    allow:
      - dependency-name: "^.*eslint.*$"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"    
 
   
