codecov:
  require_ci_to_pass: false #This setting will update the bot regardless of whether or not tests pass

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
  precision: 2
  round: down
  range: "66...100"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
