version: 2.1
orbs:
  node: circleci/node@4.5.1
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  nodetest:
    executor: node/default
    steps:
      - checkout
workflows:
  matrix-tests:
    jobs:
      - nodetest:
          version: 13.11.0
      - nodetest:
          version: 12.16.0
      - nodetest:
          version: 10.19.0
