version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  node/test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing dependencies (npm install)
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_module
      - run:
          name: npm run tests
          command: npm run test:coverage
      - run:
          name: npm run lint
          command: npm run lint    
workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 13.11.0
      - node/test:
          version: 12.16.0
      - node/test:
          version: 10.19.0
