version: 2.1
executors:
  pw-focal-development:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    environment:
      NODE_ENV: development # Needed to ensure 'dist' folder created and devDependencies installed
      BUSTED_CACHE: "false"
parameters:
  bust_cache:
    default: "false"
    type: string
commands:
  bust_cache:
    description: "Send this command with the 'Trigger Build' option in the CircleCI UI"
    steps:
      - run: echo $BUSTED_CACHE
      - run: export BUSTED_CACHE={{ epoch }}
  generate_and_store_version_artifacts:
    description: "Used to track the packages and files"
    steps:
      - run: |
          mkdir /tmp/artifacts
          printenv NODE_ENV >> /tmp/artifacts/NODE_ENV.txt
          npm -v >> /tmp/artifacts/npm-version.txt
          node -v >> /tmp/artifacts/node-version.txt
          ls -latR >> /tmp/artifacts/dir.txt
      - store_artifacts:
          path: /tmp/artifacts/
orbs:
  node: circleci/node@4.9.0
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  npm-audit:
    executor: pw-focal-development
    steps:
      - checkout
      - node/install:
          install-npm: true
          node-version: lts/fermium
      - run: npm install
      - run: npm audit --audit-level=low
      - generate_and_store_version_artifacts
  node10-lint:
    executor: pw-focal-development
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}--lts/dubnium--{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}--{{ env.BUSTED_CACHE }}
      - node/install:
          install-npm: false #Cannot install latest npm version with node10.
          node-version: lts/dubnium
      - run: npm install
      - restore_cache:
          key: deps-{{ .Branch }}--lts/dubnium--{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}--{{ env.BUSTED_CACHE }}
      - run: npm run lint
      - generate_and_store_version_artifacts
  test:
    parameters:
      node-version:
        type: string
      browser:
        type: string
    executor: pw-focal-development
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}--<< parameters.node-version >>--{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}--{{ env.BUSTED_CACHE }}
      - node/install:
          install-npm: true
          node-version: << parameters.node-version >>
      - run: npm install
      - when:
          condition:
            equal: [ "FirefoxESR", <<parameters.browser>> ]
          steps:
            - browser-tools/install-firefox:
                version: "91.4.0esr" #https://archive.mozilla.org/pub/firefox/releases/          
      - when:
          condition:
            equal: [ "FirefoxHeadless", <<parameters.browser>> ]
          steps:
            - browser-tools/install-firefox
      - when:
          condition:
            equal: [ "ChromeHeadless", <<parameters.browser>> ]
          steps:
            - browser-tools/install-chrome:
                replace-existing: false
      - save_cache:
          key: deps-{{ .Branch }}--<< parameters.node-version >>--{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}--{{ env.BUSTED_CACHE }}
          paths:
            - ~/.npm
            - node_modules
      - run: npm run test:coverage -- --browsers=<<parameters.browser>>
      - store_test_results:
          path: dist/reports/tests/
      - store_artifacts:
          path: dist/reports/
      - generate_and_store_version_artifacts
  e2e:
    parameters:
      node-version:
        type: string
      suite:
        type: string
    executor: pw-focal-development
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}--<< parameters.node-version >>--{{ checksum "package.json" }}-{{ checksum ".circleci/config.yml" }}--{{ env.BUSTED_CACHE }}
      - node/install:
          install-npm: true
          node-version: << parameters.node-version >>
      - run: npm install
      - run: npx playwright install
      - run: npm run test:e2e:<<parameters.suite>>
      - store_test_results:
          path: test-results/results.xml
      - store_artifacts:
          path: test-results
      - generate_and_store_version_artifacts
workflows:
  matrix-tests:
    jobs:
      - node10-lint
      - test:
          name: node12-chrome
          node-version: lts/erbium
          browser: ChromeHeadless
      - test: 
          name: node14-chrome
          node-version: lts/fermium
          browser: ChromeHeadless
          post-steps:
            - run:
                command:
                  curl -Os https://uploader.codecov.io/latest/linux/codecov;chmod +x codecov;./codecov 
      - e2e:
          name: e2e-smoke
          node-version: lts/fermium
          suite: ci
  nightly:
    jobs:
      - test:
          name: node10-chrome-nightly
          node-version: lts/dubnium
          browser: ChromeHeadless
      - test:
          name: node12-firefoxESR-nightly
          node-version: lts/erbium
          browser: FirefoxESR
      - test:
          name: node12-chrome-nightly
          node-version: lts/erbium
          browser: ChromeHeadless
      - test:
          name: node14-firefox-nightly
          node-version: lts/fermium
          browser: FirefoxHeadless
      - test: 
          name: node14-chrome-nightly
          node-version: lts/fermium
          browser: ChromeHeadless
      - npm-audit
      - e2e:
          name: e2e-full-nightly
          node-version: lts/fermium
          suite: full
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
