version: 2
jobs:
  build:
    docker:
        - image: circleci/node:8-browsers
          environment:
            CHROME_BIN: "/usr/bin/google-chrome"
    steps:
        - checkout
        - run:
            name: Update npm
            command: 'sudo npm install -g npm@latest'
        - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
        - run:
            name: Install npm
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "bower.json" }}
            paths:
              - node_modules
              - bower_components
        - run:
            name: test
            command: npm run test
        - run:
            name: lint
            command: npm run lint
        - run:
            name: checkstyle
            command: npm run checkstyle

workflows:
  version: 2
  test:
    jobs:
      - build
