version: 2.1
executors:
  linux:
    docker:
      - image: cimg/base:2020.01
orbs:
  node: circleci/node@4.5.1
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  test:
    parameters:
      node-version:
        type: string
      browser:
        type: string
    executor: linux
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/install-packages:
          override-ci-command: npm install
      - browser-tools/install-firefox:
          version: "78.11.0esr" #https://archive.mozilla.org/pub/firefox/releases/
      - browser-tools/install-chrome:
          replace-existing: false
      - run: npm run test:coverage --browsers=<< parameters.browser >>
      - store_test_results:
          path: dist/reports/tests/
      - store_artifacts:
          path: dist/reports/
workflows:
  matrix-tests:
    jobs:
      - test:
          name: node10-chrome
          node-version: lts/dubnium
          browser: ChromeHeadless
      - test:
          name: node12-firefox
          node-version: lts/erbium
          browser: FirefoxHeadless
      - test:
          name: node14-canary
          node-version: lts/fermium
          browser: ChromeCanaryHeadless
      - test:
          name: node16-chrome
          node-version: '16'
          browser: ChromeHeadless


