name: "e2e-pr"
on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - opened
jobs:
  e2e-full:
    if: ${{ github.event.label.name == 'pr:e2e' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Trigger Success
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: "nasa",
              repo: "openmct",
              body: 'Started e2e Run. Follow along: https://github.com/nasa/openmct/actions/runs/' + context.runId
            })
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npx playwright@1.32.3 install
      - run: npx playwright install chrome-beta
      - run: npm install
      - run: npm run test:e2e:full -- --max-failures=40
      - run: npm run cov:e2e:report || true
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.CODECOV_TOKEN }}
        run: |
          npm run cov:e2e:full:publish
      - name: Archive test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          path: test-results
      - name: Test success
        if: ${{ success() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: "nasa",
              repo: "openmct",
              body: 'Success ✅ ! Build artifacts are here: https://github.com/nasa/openmct/actions/runs/' + context.runId
            })
      - name: Test failure
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: "nasa",
              repo: "openmct",
              body: 'Failure ❌ ! Build artifacts are here: https://github.com/nasa/openmct/actions/runs/' + context.runId
            })
      - name: Remove pr:e2e label (if present)
        if: ${{ contains(github.event.pull_request.labels.*.name, 'pr:e2e') }}
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/issues/{pr_number}/labels/{name}
          # These parameters will cause warnings due to
          # a bug in the action runner. They can be ignored.
          # https://github.com/octokit/request-action/issues/26
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.pull_request.number }}
          name: 'pr:e2e'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
