name: "e2e-visual"
on:
  workflow_dispatch:
  pull_request:
    types: 
      - labeled
      - opened
  schedule:
    - cron: '28 21 * * 1-5'

jobs:
  e2e-visual:
    if: ${{ github.event.label.name == 'pr:visual' }} || ${{ github.event.workflow_dispatch }} || ${{ github.event.schedule }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }--build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}--build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - run: npx playwright install
      - run: npm install
      - name: Run the e2e visual tests
        run: npm run test:e2e:visual
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
