name: "e2e-pr"
on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  e2e-full:
    if: ${{ github.event.label.name == 'pr:e2e' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: Run all e2e tests
      - run: npm run test:e2e:full
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.pulls.createComment({
              pull_number: context.pulls.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Finished!'
            })
      