name: "pr-platform"
on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  e2e-full:
    if: ${{ github.event.label.name == 'pr:platform' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04 #MMOC Ubuntu version
          - macos-latest
          - macos-10.15
          - windows-latest
        node_version:
          - 14
          - 16
          - 17
        architecture:
          - x64
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          check-latest: true
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node_version }}--build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node_version }}--build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - run: npm install
      - run: npm test
      - run: npm run lint -- --quiet
